### Questão 1
Criando dois arrays (um de "1s" e outro aleatório), somando-os e usando a estrutura condicional `if/else` com o método `reshape()` para mudar o formato da matriz dependendo do valor da soma[cite: 7, 8].

In [6]:
import numpy as np

# Cria array de 1s e array de aleatórios de 0 a 9 (o limite superior no randint é exclusivo)[cite: 7, 8]
arr_uns = np.ones(8)
arr_aleatorios = np.random.randint(0, 10, 8)

# Somando os arrays[cite: 7]
arr_soma = arr_uns + arr_aleatorios
print(f"Array resultante da soma: {arr_soma}")

# Pegando a soma de todos os elementos[cite: 7]
soma_total = arr_soma.sum()
print(f"Soma de todos os elementos: {soma_total}")

# Condicional para o remodelamento (reshape)[cite: 7, 8]
if soma_total >= 40:
    # Matriz com mais linhas (4) do que colunas (2)
    matriz_final = arr_soma.reshape(4, 2)
    print("\nSoma >= 40. Reshape para 4x2:\n", matriz_final)
else:
    # Matriz com mais colunas (4) do que linhas (2)
    matriz_final = arr_soma.reshape(2, 4)
    print("\nSoma < 40. Reshape para 2x4:\n", matriz_final)

Array resultante da soma: [7. 5. 4. 1. 5. 7. 9. 2.]
Soma de todos os elementos: 40.0

Soma >= 40. Reshape para 4x2:
 [[7. 5.]
 [4. 1.]
 [5. 7.]
 [9. 2.]]


### Questão 2
Mini Campo Minado. Criamos a matriz com zeros, inserimos a bomba em uma posição aleatória e usamos um laço `for` com `input` para ler as 3 tentativas do usuário[cite: 7, 8].

In [3]:
import numpy as np

# a) Array 2x2 formado por zeros[cite: 7, 8]
campo = np.zeros([2, 2])

# b) Posição aleatória para a bomba (número 1)[cite: 8]
# Usamos randint(0, 2) para sortear o índice 0 ou 1 para a linha e coluna
linha_bomba = np.random.randint(0, 2, 1)[0]
coluna_bomba = np.random.randint(0, 2, 1)[0]
campo[linha_bomba, coluna_bomba] = 1

# c) Lógica do jogo (3 jogadas)[cite: 8]
venceu = True

print("--- MINI CAMPO MINADO ---")
print("Tente não encontrar a bomba (1)! O campo é uma matriz 2x2 (índices 0 e 1).")

for jogada in range(3):
    linha_jogada = int(input(f"Jogada {jogada+1} - Digite a linha (0 ou 1): "))
    coluna_jogada = int(input(f"Jogada {jogada+1} - Digite a coluna (0 ou 1): "))

    # Verifica se acertou a bomba
    if campo[linha_jogada, coluna_jogada] == 1:
        print("\nGame Over!: (Try Again!)")
        venceu = False
        break
    else:
        print("Ufa! Posição segura.\n")

if venceu:
    print("Congratulations! You beat the game! :)")

--- MINI CAMPO MINADO ---
Tente não encontrar a bomba (1)! O campo é uma matriz 2x2 (índices 0 e 1).
Jogada 1 - Digite a linha (0 ou 1): 1
Jogada 1 - Digite a coluna (0 ou 1): 1

Game Over!: (Try Again!)


### Questão 3
Extraindo propriedades da matriz com `shape`, multiplicando linhas por colunas e verificando se o resultado (tamanho caso virasse um vetor) é par ou ímpar[cite: 7, 8].

In [4]:
import numpy as np

# Matriz de tamanho qualquer (ex: 3x4 de zeros)[cite: 7, 8]
mtz = np.zeros([3, 4])

# O shape retorna uma tupla. O índice 0 é linha, e o índice 1 é coluna[cite: 7]
linhas = mtz.shape[0]
colunas = mtz.shape[1]

# Multiplicando para saber o total de elementos (mesmo que usar mtz.size)
total_elementos = linhas * colunas

print(f"A matriz tem {linhas} linhas e {colunas} colunas. Total = {total_elementos} elementos.")

# Verifica se é par ou ímpar
if total_elementos % 2 == 0:
    print("Esta matriz poderia se tornar um vetor unidimensional com número PAR de elementos.")
else:
    print("Esta matriz poderia se tornar um vetor unidimensional com número ÍMPAR de elementos.")

A matriz tem 3 linhas e 4 colunas. Total = 12 elementos.
Esta matriz poderia se tornar um vetor unidimensional com número PAR de elementos.


### Questão 4
Uso de Sementes Aleatórias (`seed`), médias por eixos (`axis=0` e `axis=1`), Slicing com condicionais e contagem de itens únicos (`return_counts=True`)[cite: 7, 8].

In [5]:
import numpy as np

# Definindo a semente para resultados iguais[cite: 7, 8]
np.random.seed(10)

# Criando matriz 4x4 com inteiros entre 1 e 50 (51 exclusivo)[cite: 7, 8]
mtz = np.random.randint(1, 51, [4, 4])
print("Matriz Gerada:\n", mtz)

# a) Média de cada linha (axis=1) e coluna (axis=0)[cite: 7, 8]
media_linhas = mtz.mean(axis=1)
media_colunas = mtz.mean(axis=0)
print("\nMédia das linhas:", media_linhas)
print("Média das colunas:", media_colunas)

# b) Maior valor das médias[cite: 7, 8]
print("\nMaior média das linhas:", media_linhas.max())
print("Maior média das colunas:", media_colunas.max())

# c) Quantidade de aparições e números que aparecem 2 vezes[cite: 7, 8]
unicos, contagens = np.unique(mtz, return_counts=True)
print("\nElementos únicos da matriz:", unicos)
print("Frequência de cada elemento:", contagens)

# Usando condicional como filtro no array (Slicing avançado ensinado no slide)[cite: 7]
# Retornamos os elementos do array 'unicos' onde a 'contagens' é igual a 2
aparecem_duas_vezes = unicos[contagens == 2]
print("\nNúmeros que aparecem exatamente 2 vezes na matriz:", aparecem_duas_vezes)

Matriz Gerada:
 [[10 37 16  1]
 [50 29 26 30]
 [49 30 50  9]
 [10  1 43 41]]

Média das linhas: [16.   33.75 34.5  23.75]
Média das colunas: [29.75 24.25 33.75 20.25]

Maior média das linhas: 34.5
Maior média das colunas: 33.75

Elementos únicos da matriz: [ 1  9 10 16 26 29 30 37 41 43 49 50]
Frequência de cada elemento: [2 1 2 1 1 1 2 1 1 1 1 2]

Números que aparecem exatamente 2 vezes na matriz: [ 1 10 30 50]


### Questão 5
Somando matrizes (zeros e uns), aplicando *Broadcasting* (multiplicação por escalar) e remodelando para 1D (vetor)[cite: 7, 8].

In [ ]:
import numpy as np

# Matrizes 3x3 de zeros e uns[cite: 7, 8]
mtz_zeros = np.zeros([3, 3])
mtz_uns = np.ones([3, 3])

# Soma elemento a elemento[cite: 7, 8]
mtz_soma = mtz_zeros + mtz_uns

# Multiplicando por um escalar de minha escolha (ex: 7)[cite: 7]
mtz_mult = mtz_soma * 7

# Remodelando para um array unidimensional de 9 elementos[cite: 7, 8]
arr_1d = mtz_mult.reshape(9)

print("Array unidimensional final:\n", arr_1d)

### Questão 6
Criando arrays espaçados usando `arange` e buscando propriedades de valores e índices (`max`, `argmax`, `min`, `argmin`, `sum`)[cite: 7, 8].

In [ ]:
import numpy as np

# Array de 10 a 30 de 2 em 2 (usamos 31 para incluir o 30)[cite: 7, 8]
arr = np.arange(10, 31, 2)
print("Array gerado:", arr)

# Maior valor e seu índice[cite: 7, 8]
print(f"Maior valor: {arr.max()} | Índice: {arr.argmax()}")

# Menor valor e seu índice[cite: 7, 8]
print(f"Menor valor: {arr.min()} | Índice: {arr.argmin()}")

# Soma de todos os elementos[cite: 7, 8]
print(f"Soma total: {arr.sum()}")

### Questão 7
Concatenação de dois Arrays NumPy e mudança estrutural para Matriz[cite: 7, 8].

In [ ]:
import numpy as np

# Semente definida na questão[cite: 8]
np.random.seed(7)

# Dois arrays 1D tamanho 5 (números entre 1 e 10 - então 1 a 11 exclusivo)[cite: 7, 8]
arr1 = np.random.randint(1, 11, 5)
arr2 = np.random.randint(1, 11, 5)

print("Array 1:", arr1)
print("Array 2:", arr2)

# Concatenando os dois (note os duplos parênteses na sintaxe do método)[cite: 7, 8]
arr3 = np.concatenate((arr1, arr2))
print("Array concatenado:", arr3)

# Transformando em matriz 2 linhas e 5 colunas[cite: 8]
mtz_final = arr3.reshape(2, 5)
print("\nMatriz Final 2x5:\n", mtz_final)